### PR TITLE
added parameter 'custom_terms' to function [clean.prepare_terms()].

### PR DESCRIPTION
**Pull request by maxu777**
added parameter 'custom_terms' to function [clean.prepare_terms()]. 
So that a user can easily construct terms including those that are missing in the module

### CODE REVIEW

**Comment by petri** [comment]
@maxu777 Thanks for the PR. I've never seen the `|=` operator used this way for sets. Is the applicability of the operator to sets documented somewhere? If that can be confirmed, I will then merge this before releasing 2.1.

**Comment by maxu777** [comment]
Hi,
i think it's described very well here:
https://stackoverflow.com/questions/3929278/what-does-ior-do-in-python

Best,
max

**Comment by petri** [comment]
Thanks @maxu777 ... I was looking for something more authoritative and lo & behold indeed it exists: https://docs.python.org/3.8/library/stdtypes.html#set-types-set-frozenset . Will merge.

**Comment by petri** [comment]
@maxu777 your PR fails on master; I had to revert it. I can take a second look if you're like to resubmit your PR fixed so it works. Please add a test this time for the new functionality.

**Pull request merged**
